### ISSUE TITLE
Why I Deleted This Plugin?

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [xXNiceAssasinl0/CrateUI#1]
I delete it cause I  accidentally create branch so I don’t know how to remove it so create new one!

**Comment by DevCreationAI** [comment]
Dont let it depend on FormsAPI plugin

**Comment by xXNiceAssasinl0** [comment]
Why

**Comment by xXNiceAssasinl0** [comment]
I fixed it now you don’t need FormAPI Plugin to work CrateUI :)!

**Comment by DevCreationAI** [comment]
Thanks!

**Comment by BurritoMan46** [comment]
Can u add like "/setcrate <common,rare,mythic,vote,legendary" command and sets a chest crate like open it with a key and get your reward?

**Comment by DevCreationAI** [comment]
As this on Sophie too ^

**Comment by xXNiceAssasinl0** [comment]
I’ll try @BurritoMan46

**Comment by BurritoMan46** [comment]
@xXNiceAssasinl0  ok

**Comment by BurritoMan46** [comment]
When you finish amount please add /setcrate?

**Comment by xXNiceAssasinl0** [comment]
Idk @BurritoMan46

**Comment by BurritoMan46** [comment]
Ok maybe don't add /setcrate add people can buy crate keys @xXNiceAssasinl0

**Comment by xXNiceAssasinl0** [comment]
Ohh buy crate gud idea

**Comment by BurritoMan46** [comment]
Thanks! 😊
