### ISSUE TITLE
Crate not opening

### ISSUE THREAD

**Issue by TBNRItzDoge25** [xXNiceAssasinl0/CrateUI#1]
I’m using CrateUI and whenever I go into the UI. I select the crate with the key in hand and nothing happens.

**Comment by xXNiceAssasinl0** [comment]
Can I join ur server? And try

**Comment by TBNRItzDoge25** [comment]
Yes ip nitronetwork.ddns.net port: 19132

**Comment by TBNRItzDoge25** [comment]
ill be online.

**Comment by TBNRItzDoge25** [comment]
My Discord is TBNRItzDoge#2707 msg me there

**Comment by xXNiceAssasinl0** [comment]
I am sorry but this plugin requirement is FormAPI Here:

https://github.com/jojoe77777/FormAPI

**Comment by TBNRItzDoge25** [comment]
.phar please?

**Comment by xXNiceAssasinl0** [comment]
you don’t need Phar download DevTools and use source code

**Comment by TBNRItzDoge25** [comment]
Ah okay

**Comment by TBNRItzDoge25** [comment]
how so walk me through it. i’m bad at code lol

**Comment by xXNiceAssasinl0** [comment]
Go Download DEvTools.phar from poggit

**Comment by TBNRItzDoge25** [comment]
yea thats download and installed into server

**Comment by TBNRItzDoge25** [comment]
@xXNiceAssasinl0 now what

**Comment by xXNiceAssasinl0** [comment]
Download [this](https://poggit.pmmp.io/r/17169/CrateUI_dev-5.phar)

**Comment by TBNRItzDoge25** [comment]
then @xXNiceAssasinl0

**Comment by xXNiceAssasinl0** [comment]
Then it should work
