### ISSUE TITLE
Commands.

### ISSUE THREAD

**Issue by GageGamesHD** [xXNiceAssasinl0/CrateUI#14]
When I try to give myself a key using the KeyUI, it never gives me the key.

When I do /key (all of the keys I have tried) and then my username, it says An unknown error has occurred while attempting to preform this command. Please fix as this looks like an EPIC crate pluign

**Comment by PotatoeTrainYT** [comment]
ok thanks for opening this issue, we will look into and fix is shortly

**Comment by PotatoeTrainYT** [comment]
I Fixed The Error, When Assasin Gets On He Will Merge The PR
