### ISSUE TITLE
Crates Not Opening

### ISSUE THREAD

**Issue by GageGamesHD** [xXNiceAssasinl0/CrateUI#16]
Hello,

I am having an issue where after I get a key, I do /crate then click on a common crate and nothing happens. It does this for all of the crates. Please fix this as I would love to see this working!

**Comment by PotatoeTrainYT** [comment]
Ok, will have a look into it! Will be fixed shortly

**Comment by PotatoeTrainYT** [comment]
Well ok, that's weird because it works for me, send your config because you may of messed something up by accident while editing it

**Comment by GageGamesHD** [comment]
I never even touched the config

**Comment by GageGamesHD** [comment]
Maybe it's another plugin messing it up?

**Comment by PotatoeTrainYT** [comment]
yes that could be it, send me a list of all your plugins

**Comment by GageGamesHD** [comment]
[https://imgur.com/a/ttDiY](url)

**Comment by GageGamesHD** [comment]
https://imgur.com/a/ttDiY

**Comment by GageGamesHD** [comment]
![bandicam 2017-12-28 06-46-36-118](https://user-images.githubusercontent.com/34907865/34409955-e6708a40-eb81-11e7-80b8-96ede6fdeae5.jpg)

**Comment by PotatoeTrainYT** [comment]
yeah its another plugin, KitUI & ProfileUI

**Comment by GageGamesHD** [comment]
Let me see real quick

**Comment by GageGamesHD** [comment]
Didn't work

**Comment by GageGamesHD** [comment]
Its still messed up. I can send you a video of what is happening

**Comment by PotatoeTrainYT** [comment]
try without plugins

**Comment by GageGamesHD** [comment]
I need the other ones though

**Comment by GageGamesHD** [comment]
Maybe its the developers issue?

**Comment by GageGamesHD** [comment]
ok

**Comment by GageGamesHD** [comment]
It worked!!!!!!

**Comment by GageGamesHD** [comment]
Do you have an idea of what could be stopping it?

**Comment by PotatoeTrainYT** [comment]
yeah so it was a plugin

**Comment by PotatoeTrainYT** [comment]
do u have any other uis?

**Comment by GageGamesHD** [comment]
umm

**Comment by GageGamesHD** [comment]
I have a shop ui

**Comment by GageGamesHD** [comment]
I just tested it without shop ui. That is what the issue was

**Comment by GageGamesHD** [comment]
Thanks for the help!

**Comment by PotatoeTrainYT** [comment]
No problem! mind closing both your issues since they are fixed?

**Comment by GageGamesHD** [comment]
Wait, is there a way to have both plugins without either of them breaking?

**Comment by QuiverlyRivalry** [comment]
Use my shopui plugin, it doesn’t break other ui plugins unlike fuckingdevs

**Comment by PotatoeTrainYT** [comment]
haha
