### ISSUE TITLE
** Important **

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [xXNiceAssasinl0/CrateUI#2]
I just added You do not need FormAPI Plugin to work it, Thank for asking @DevCreationAI

**Comment by armagadon159753** [comment]
Why not implment in your plugin

**Comment by xXNiceAssasinl0** [comment]
?

**Comment by xXNiceAssasinl0** [comment]
Just added /key <key> <player>

Trying to add amount now

**Comment by xXNiceAssasinl0** [comment]
no /key <key> <player> <amount> I am working on amount lol

**Comment by armagadon159753** [comment]
Ooh ok if you want i can make the implémentation of FormAPI in  you plugin?

**Comment by xXNiceAssasinl0** [comment]
U have discord

**Comment by armagadon159753** [comment]
ArmTheDev#9575
