### ISSUE TITLE
Add on console

### ISSUE THREAD

**Issue by 0pGam3rMC** [xXNiceAssasinl0/CrateUI#4]
Hey just curious how can I have my console automatically give keys like when someone /vote or something

**Comment by xXNiceAssasinl0** [comment]
Okay console can’t give key it doesn’t have img I’ll try

**Comment by 0pGam3rMC** [comment]
Alright thanks, okay when I give myself a key and open Crate GUI then tap a
crate I do not receive anything..instead an error on console.

**Comment by xXNiceAssasinl0** [comment]
Please create a issue for a error @0pGam3rMC

**Comment by xXNiceAssasinl0** [comment]
Added
