### ISSUE TITLE
Ability To add Ranks

### ISSUE THREAD

**Issue by BigDGucci** [xXNiceAssasinl0/CrateUI#8]
I was asking if you could add the ability to add ranks for example. You get item says the certain rank. Tap on ground. It redeems. And removes from inv. You could make an addon for this plugin with my suggestion. i think it would be really cool. :) With pure perms and pure chat

**Comment by xXNiceAssasinl0** [comment]
I don’t really understand.

**Comment by BigDGucci** [comment]
@xXNiceAssasinl0 
https://www.youtube.com/watch?v=bOiGDDbsM8w&t=2s

**Comment by xXNiceAssasinl0** [comment]
I’ll try to add it

**Comment by BigDGucci** [comment]
Your the best. Plus im subbed to u. Also this is a suggestion, you don't have to do it

**Comment by xXNiceAssasinl0** [comment]
I will try my best to add it 😉

**Comment by PotatoeTrainYT** [comment]
@BigDGucci If He Does This, You Would Have To Make Your Own Plugin Making The Voucher Into A Thing Which Gives The Rank
